export const ProjectList = [
  {
    name: "Multipage E-Learning Platform",
    image: "/assets/proj1.png",
    skills: "Javascript, Jquery, CSS, HTML",
    githubUrl: "https://github.com/Ovsclassic/Multipage-Educational-Website",
    website: "https://educational-js.netlify.app/",
    id: "0",
  },
  {
    name: "Notes App",
    image: "/assets/proj2.png",
    skills: "Javascript, React, CSS3, HTML5",
    githubUrl: "https://github.com/Ovsclassic/NoteApp",
    website: "https://note-app-6pks.vercel.app/",
    id: "1",
  },
  {
    name: "Gradient Colors Website",
    image: "/assets/proj3.png",
    skills: "Javascript, JQuery, CSS, HTML",
    githubUrl: "https://github.com/Ovsclassic/WebsiteJS---colors",
    website: "https://colorswebsite.netlify.app",
    id: "2",
  },
  {
    name: "Admin Dashboard Visualizer",
    image: "/assets/proj4.png",
    skills: "Javascript, Jquery, CSS, HTML",
    githubUrl: "https://github.com/Ovsclassic/Admin-Dashboard",
    website: "https://ovsadminwebsite.netlify.app",
    id: "3",
  },
  {
    name: "E-Commerce Website",
    image: "/assets/proj5.png",
    skills: "React.js, Javascript, Api, CSS, HTML",
    githubUrl: "https://github.com/Ovsclassic/cartshop",
    website: "https://cartshop.netlify.app",
    id: "4",
  },
  {
    name: "Artificial Intelligence Website",
    image: "/assets/proj6.png",
    skills: "React.js, Javascript, CSS, HTML, Tailwind CSS",
    githubUrl: "https://github.com/Ovsclassic/crypto-project",
    website: "https://open-ai-future.netlify.app/",
    id: "5",
  },
];
